use_frameworks!

target 'SwifyCloudKit_tvOS' do 
  platform :tvos, '10.0'
  pod 'SwiftyCloudKit', :path => '../'
end

target 'SwiftyCloudKit_watchOS' do 
  platform :watchos, '3.0'
  pod 'SwiftyCloudKit', :path => '../'
end

target 'SwiftyCloudKit_Example' do
  platform :ios, '10.0'
  pod 'SwiftyCloudKit', :path => '../'

  target 'SwiftyCloudKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
