use_frameworks!

target 'SwiftyCloudKit_Example' do
  pod 'SwiftyCloudKit', :path => '../'

  target 'SwiftyCloudKit_Tests' do
    inherit! :search_paths

    use_frameworks!
    pod 'Nimble' 
  end
end
